### ISSUE TITLE
PSDSCPullServer.svc API Documentation

### ISSUE THREAD

**Issue by farzaaaan** [dsccommunity/xPSDesiredStateConfiguration#443]
Hi, 

I've been looking around for any documentation on the PSDSC web service, but have not had any luck so far. I'm looking for available calls through url for Nodes, Reports, etc. so that I can make specific calls to the web service. 

going directly to http://server:8080/PSDSCPullServer.svc does not bring up any help page, and $metadata doesn't seem to be all that helpful either.

any help is greatly appreciated,
Thanks

**Comment by johlju** [comment]
Only I can think of is [[MS-DSCPM]: Desired State Configuration Pull Model Protocol](https://msdn.microsoft.com/library/dn393548.aspx).

If that doesn't help, since the Windows Pull Server is part of Windows Server, I suggest that you submit a [user voice](https://windowsserver.uservoice.com/forums/301869-powershell?category_id=148047) for any information you think is missing
